### ISSUE TITLE
Prompt for active key on disabled

### ISSUE THREAD

**Issue by themarkymark-steem** [witness-essentials/cli#3]
With HF20 you can change keys w/ your private witness key which is a fantastic change and I was excited you added this functionality.  One problem is when your witness is disabled, you then need an active key to re-enable it.  Currently, you have to put it in the config file or activate outside of this tool.

What I suggest if it does not have a key, it will prompt on the command line.  That way I can enter the activate key but it won't be stored on the file system anywhere.

**Comment by therealwolf42** [comment]
Great idea. Added the feature to the newest update.
